Update Jenkinsfile

diff --git a/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile b/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
--- a/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
+++ b/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
@@ -19,7 +19,7 @@ pipeline {
         string(
             name: 'TFVARS_FILE',
             defaultValue: 'terraform.tfvars',
-            description: 'Terraform variable file name'
+            description: 'Enter Terraform variables file name (.tfvars)'
         )
 
     }
@@ -61,28 +61,42 @@ pipeline {
 
 
 
+
+
         stage('Environment Check') {
 
             steps {
 
+
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
+
                     sh '''
+
+                    echo "=============================="
 
                     echo "Terraform Version"
 
                     terraform version
 
 
-                    echo "AWS Account"
+                    echo "=============================="
+
+                    echo "AWS Identity"
 
                     aws sts get-caller-identity
 
 
+                    echo "=============================="
+
                     echo "Terraform Files"
+
+                    ls -ltr *.tf
 
                     ls -ltr *.tfvars
 
+
+                    echo "=============================="
 
                     '''
 
@@ -96,6 +110,8 @@ pipeline {
 
 
 
+
+
         stage('Set Terraform State') {
 
             steps {
@@ -103,15 +119,15 @@ pipeline {
                 script {
 
 
-                    def envName = params.TFVARS_FILE
-                                    .replace('.tfvars','')
+                    def stateName = params.TFVARS_FILE
+                                      .replace('.tfvars','')
 
 
-                    env.TF_STATE_KEY = "${envName}/terraform.tfstate"
+                    env.TF_STATE_KEY = "${stateName}/terraform.tfstate"
 
 
-                    echo "Terraform State:"
-                    echo "${env.TF_STATE_KEY}"
+                    echo "Using Terraform State:"
+                    echo "${TF_STATE_KEY}"
 
 
                 }
@@ -126,9 +142,51 @@ pipeline {
 
 
 
-        stage('Terraform Init') {
+
+        stage('Validate TFVARS File') {
+
 
             steps {
+
+
+                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
+
+
+                    sh """
+
+                    if [ ! -f ${params.TFVARS_FILE} ]; then
+
+                        echo "${params.TFVARS_FILE} not found"
+
+                        exit 1
+
+                    fi
+
+
+                    echo "Using:"
+                    echo "${params.TFVARS_FILE}"
+
+
+                    """
+
+                }
+
+            }
+
+        }
+
+
+
+
+
+
+
+
+        stage('Terraform Init') {
+
+
+            steps {
+
 
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
@@ -136,6 +194,7 @@ pipeline {
                     sh """
 
                     terraform init \
+                    -reconfigure \
                     -backend-config="key=${TF_STATE_KEY}"
 
 
@@ -153,6 +212,7 @@ pipeline {
 
 
 
+
         stage('Terraform Validate') {
 
 
@@ -162,11 +222,11 @@ pipeline {
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
 
-                    sh """
+                    sh '''
 
                     terraform validate
 
-                    """
+                    '''
 
                 }
 
@@ -210,6 +270,7 @@ pipeline {
 
                     terraform plan \
                     -var-file=${params.TFVARS_FILE} \
+                    -lock-timeout=5m \
                     -out=tfplan
 
 
@@ -275,7 +336,6 @@ pipeline {
 
 
 
-
         stage('Terraform Destroy') {
 
 
@@ -304,7 +364,8 @@ pipeline {
 
                     terraform destroy \
                     -auto-approve \
-                    -var-file=${params.TFVARS_FILE}
+                    -var-file=${params.TFVARS_FILE} \
+                    -lock-timeout=5m
 
 
                     """
@@ -317,6 +378,7 @@ pipeline {
 
 
     }
+
 
 
 
@@ -343,6 +405,8 @@ pipeline {
 
         }
 
+
     }
+
 
 }
