Update Jenkinsfile

diff --git a/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile b/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
--- a/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
+++ b/terraform-ec2-jenkins/terraform-ec2-jenkins/Jenkinsfile
@@ -32,12 +32,6 @@ pipeline {
 
         timestamps()
 
-        buildDiscarder(
-            logRotator(
-                numToKeepStr: '10'
-            )
-        )
-
     }
 
 
@@ -52,9 +46,7 @@ pipeline {
 
 
 
-
     stages {
-
 
 
         stage('Checkout Code') {
@@ -69,56 +61,35 @@ pipeline {
 
 
 
-
-
         stage('Environment Check') {
 
             steps {
 
-
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
-
 
                     sh '''
 
                     echo "=============================="
-
                     echo "Current User"
-
                     whoami
 
-
                     echo "=============================="
-
                     echo "Current Directory"
-
                     pwd
 
-
                     echo "=============================="
-
                     echo "Terraform Version"
-
                     terraform version
 
-
                     echo "=============================="
-
                     echo "AWS Identity"
-
                     aws sts get-caller-identity
 
-
                     echo "=============================="
-
                     echo "Terraform Files"
-
-                    ls -ltr *.tf
-                    ls -ltr *.tfvars
-
+                    ls -ltr
 
                     echo "=============================="
-
 
                     '''
 
@@ -132,30 +103,24 @@ pipeline {
 
 
 
-
-
         stage('Validate TFVARS File') {
-
 
             steps {
 
-
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
-
 
                     sh """
 
                     if [ ! -f ${params.TFVARS_FILE} ]; then
 
-                    echo "ERROR: ${params.TFVARS_FILE} does not exist"
+                        echo "ERROR: ${params.TFVARS_FILE} not found"
 
-                    exit 1
+                        exit 1
 
                     fi
 
 
                     echo "Using Terraform Variable File: ${params.TFVARS_FILE}"
-
 
                     """
 
@@ -169,16 +134,11 @@ pipeline {
 
 
 
-
-
         stage('Terraform Init') {
-
 
             steps {
 
-
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
-
 
                     sh '''
 
@@ -196,16 +156,11 @@ pipeline {
 
 
 
-
-
         stage('Terraform Validate') {
-
 
             steps {
 
-
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
-
 
                     sh '''
 
@@ -223,14 +178,9 @@ pipeline {
 
 
 
-
-
-
         stage('Terraform Plan') {
 
-
             when {
-
 
                 expression {
 
@@ -242,19 +192,17 @@ pipeline {
             }
 
 
-
             steps {
-
 
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
-
                     sh """
+
+                    echo "Running Terraform Plan"
 
                     terraform plan \
                     -var-file=${params.TFVARS_FILE} \
                     -lock-timeout=5m
-
 
                     """
 
@@ -263,46 +211,6 @@ pipeline {
             }
 
         }
-
-
-
-
-
-
-
-
-
-        stage('Terraform Apply Approval') {
-
-
-            when {
-
-
-                expression {
-
-                    params.ACTION == 'APPLY'
-
-                }
-
-            }
-
-
-
-            steps {
-
-
-                input(
-
-                    message: 'Approve Terraform Apply?',
-
-                    ok: 'Proceed'
-
-                )
-
-            }
-
-        }
-
 
 
 
@@ -312,9 +220,7 @@ pipeline {
 
         stage('Terraform Apply') {
 
-
             when {
-
 
                 expression {
 
@@ -325,20 +231,18 @@ pipeline {
             }
 
 
-
             steps {
-
 
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
-
                     sh """
+
+                    echo "Running Terraform Apply"
 
                     terraform apply \
                     -auto-approve \
                     -var-file=${params.TFVARS_FILE} \
                     -lock-timeout=5m
-
 
                     """
 
@@ -354,51 +258,9 @@ pipeline {
 
 
 
-
-
-        stage('Terraform Destroy Approval') {
-
-
-            when {
-
-
-                expression {
-
-                    params.ACTION == 'DESTROY'
-
-                }
-
-            }
-
-
-
-            steps {
-
-
-                input(
-
-                    message: 'WARNING: Destroy Infrastructure?',
-
-                    ok: 'Destroy'
-
-                )
-
-            }
-
-        }
-
-
-
-
-
-
-
-
         stage('Terraform Destroy') {
 
-
             when {
-
 
                 expression {
 
@@ -409,20 +271,18 @@ pipeline {
             }
 
 
-
             steps {
-
 
                 dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {
 
-
                     sh """
+
+                    echo "Running Terraform Destroy"
 
                     terraform destroy \
                     -auto-approve \
                     -var-file=${params.TFVARS_FILE} \
                     -lock-timeout=5m
-
 
                     """
 
@@ -434,7 +294,6 @@ pipeline {
 
 
     }
-
 
 
 
